# Generated by Django 5.1.1 on 2024-09-29 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Assurance Goals',
                'db_table': 'assurance_goal',
            },
        ),
        migrations.CreateModel(
            name='FairnessApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Fairness Approaches',
                'db_table': 'fairness_approach',
            },
        ),
        migrations.CreateModel(
            name='ProjectLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project Lifecycle Stages',
                'db_table': 'project_lifecycle_stage',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('assurance_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assurancegoal')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assurance_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assurancegoal')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('model_dependency', models.CharField(max_length=255)),
                ('example_use_case', models.TextField()),
                ('scope', models.CharField(blank=True, max_length=255, null=True)),
                ('assurance_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assurancegoal')),
            ],
            options={
                'verbose_name_plural': 'Techniques',
                'db_table': 'technique',
            },
        ),
        migrations.CreateModel(
            name='TechniqueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'verbose_name_plural': 'Technique Categories',
                'db_table': 'technique_category',
                'unique_together': {('technique', 'category')},
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='categories',
            field=models.ManyToManyField(blank=True, through='api.TechniqueCategory', to='api.category'),
        ),
        migrations.CreateModel(
            name='TechniqueSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'verbose_name_plural': 'Technique Sub-Categories',
                'db_table': 'technique_sub_category',
                'unique_together': {('technique', 'sub_category')},
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, through='api.TechniqueSubCategory', to='api.subcategory'),
        ),
        migrations.CreateModel(
            name='TechniqueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'verbose_name_plural': 'Technique Tags',
                'db_table': 'technique_tag',
                'unique_together': {('technique', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='technique',
            name='tags',
            field=models.ManyToManyField(blank=True, through='api.TechniqueTag', to='api.tag'),
        ),
        migrations.CreateModel(
            name='TechniqueFairnessApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fairness_approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fairnessapproach')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'db_table': 'technique_fairness_approach',
                'unique_together': {('technique', 'fairness_approach')},
            },
        ),
        migrations.CreateModel(
            name='TechniqueProjectLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_lifecycle_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectlifecyclestage')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'db_table': 'technique_project_lifecycle_stage',
                'unique_together': {('technique', 'project_lifecycle_stage')},
            },
        ),
        migrations.CreateModel(
            name='TechniqueProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.technique')),
            ],
            options={
                'verbose_name_plural': 'Technique Properties',
                'db_table': 'technique_property',
                'unique_together': {('technique', 'property')},
            },
        ),
    ]
