# Generated by Django 5.1.1 on 2024-09-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TechniqueCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories')),
            ],
            options={
                'db_table': 'technique_categories',
            },
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('scope_global', models.BooleanField(blank=True, null=True)),
                ('scope_local', models.BooleanField(blank=True, null=True)),
                ('model_dependency', models.CharField(blank=True, max_length=50, null=True)),
                ('example_use_case', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='techniques', through='api.TechniqueCategories', to='api.categories')),
            ],
            options={
                'db_table': 'techniques',
            },
        ),
        migrations.AddField(
            model_name='techniquecategories',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techniques'),
        ),
        migrations.CreateModel(
            name='TechniqueTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tags')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techniques')),
            ],
            options={
                'db_table': 'technique_tags',
                'unique_together': {('technique', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='techniques',
            name='tags',
            field=models.ManyToManyField(related_name='techniques', through='api.TechniqueTags', to='api.tags'),
        ),
        migrations.AlterUniqueTogether(
            name='techniquecategories',
            unique_together={('technique', 'category')},
        ),
        migrations.CreateModel(
            name='SubTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcategories')),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.techniques')),
            ],
            options={
                'db_table': 'sub_techniques',
                'unique_together': {('technique', 'sub_category')},
            },
        ),
        migrations.AddIndex(
            model_name='techniques',
            index=models.Index(fields=['technique'], name='techniques_technique_idx'),
        ),
    ]
